name: the_book_store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  language_picker: ^0.4.5
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/Vector.png
    - lib/assets/images/author1.png
    - lib/assets/images/author2.png
    - lib/assets/images/author3.png
    - lib/assets/images/book1.png
    - lib/assets/images/book2.png
    - lib/assets/images/book3.png
    - lib/assets/images/book.png
    - lib/assets/images/Frame.png
    - lib/assets/data.json
    - lib/assets/images/pub1.png
    - lib/assets/images/pub2.png
    - lib/assets/images/pub3.png
    - lib/assets/images/pub4.png
    - lib/assets/images/google.png
    - lib/assets/images/apple.png
    - lib/assets/images/cart1.png
    - lib/assets/images/cart2.png
    - lib/assets/images/cart3.png
